### ISSUE TITLE
Long und Lat in Location are rounded -- unfortunately

### ISSUE THREAD

**Issue by fischhasegbr** [georgringer/eventnews#123]
Hallo Georg,

Eventnews is one of my favourite extensions. Thank you. Now I found one serious problem with the locations. I use the location list for Meetingpoints in nature reserve areas. Now it came out, that lat and long are rounded to two decimal places. That make a huge different in real. 

![eventnews_coords](https://user-images.githubusercontent.com/89974854/131826815-305d0b76-a78e-48df-97e3-03b4f5eabc6f.jpg)

Thanks für fixing. 
Viele Grüße
Martin

**Comment by skrude61** [comment]
See my pull request #113
