### ISSUE TITLE
Support for TYPO3 11 ?

### ISSUE THREAD

**Issue by stigfaerch** [georgringer/eventnews#124]
Is support for TYPO3 11 in the works?

**Comment by stigfaerch** [comment]
> not really yet, wanna provide a PR?
@georgringer I did - have you had a look?

**Comment by DavidBruchmann** [comment]
@stigfaerch I remarked incontinences in namespace

 - GeorgRinger\Eventnews
 - GeorgRinger\EventNews 

The second solution shouldn't be used

**Comment by DavidBruchmann** [comment]
@stigfaerch the whole constructor is not required, I opened issue #127 for it.

**Comment by georgringer** [comment]
fixed now

**Comment by DavidBruchmann** [comment]
Thanks a lot, to both of you!

**Comment by DanielSiepmann** [comment]
https://github.com/georgringer/eventnews/blob/207b7009abe2e1e4c450d2e2ddf07c22c8aebd98/composer.json states the extension now is compatible with v11. Is there any release planed so far to release v11 compatible version, or is there anything left to do?

**Comment by DavidBruchmann** [comment]
in composer.json I use this currently:
```
		"georgringer/news": "dev-main as 9.2.0",
		"georgringer/eventnews": "dev-main",
```

**Comment by DanielSiepmann** [comment]
Should finaly be finished via latest release: https://github.com/georgringer/eventnews/releases/tag/5.0.0
