### ISSUE TITLE
remove controller-constructor

### ISSUE THREAD

**Issue by DavidBruchmann** [georgringer/eventnews#127]
The controller-constructor is instantiating only the locationRepository which is instantiated in local context in monthAction.
Therefore $this->locationRepository is not required or just could be assigned in the monthAction.

The primary reason for the removal of the constructor is another though:  
The cacheManager of news is parsing the constructor-method wrong and is producing an ErrorMessage (503).

Additional Background:  
- https://github.com/georgringer/eventnews/issues/125 is installed.
- https://github.com/georgringer/news/pull/1639 is installed, but is never fixing any issues with the controller.

**Comment by georgringer** [comment]
fixewd

**Comment by DavidBruchmann** [comment]
thanks a lot!
