### ISSUE TITLE
Recurring events not possible

### ISSUE THREAD

**Issue by emileblume** [georgringer/eventnews#128]
There is no option to create recurring events

**Comment by georgringer** [comment]
there is no feature like that and also not planned

**Comment by emileblume** [comment]
Bummer

**Comment by DavidBruchmann** [comment]
@emileblume you can have a look here to find perhaps what you're looking for:  
https://github.com/lochmueller/calendarize

**Comment by emileblume** [comment]
@DavidBruchmann Thanks for the suggestion but this will require adding a new extension. We want to keep the extension list as short as possible. We are going to use the Top News option as an alternative.
