### ISSUE TITLE
TCA migrations that need still to be applied

### ISSUE THREAD

**Issue by angeloprevitali** [georgringer/eventnews#13]
Hello Georg

on the updated version there are still some TCA migrations that need to be applied. 
Can you please adapt them?

Thanks.

Regards,
Angelo

The icon path of wizard "link" from TCA table "tx_eventnews_domain_model_organizer['columns']['link']['config']['wizards']['link']['icon']"has been migrated to tx_eventnews_domain_model_organizer['columns']['link']['config']['wizards']['link']['icon']" = 'actions-wizard-link'.

The TCA setting 'versioningWS' was set to a boolean value in TCA tx_eventnews_domain_model_location['ctrl']['versioningWS']

The TCA setting 'versioning_followPages' was removed as it is unused in TCA tx_eventnews_domain_model_location['ctrl']['versioning_followPages']

The TCA setting 'versioningWS' was set to a boolean value in TCA tx_eventnews_domain_model_organizer['ctrl']['versioningWS']

The TCA setting 'versioning_followPages' was removed as it is unused in TCA tx_eventnews_domain_model_organizer['ctrl']['versioning_followPages']

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_eventnews_domain_model_location['columns']['starttime']['l10n_mode'] and changed to tx_eventnews_domain_model_location['columns']['starttime']['config']['behaviour']['allowLanguageSynchronization'] = true

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_eventnews_domain_model_location['columns']['endtime']['l10n_mode'] and changed to tx_eventnews_domain_model_location['columns']['endtime']['config']['behaviour']['allowLanguageSynchronization'] = true

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_eventnews_domain_model_organizer['columns']['starttime']['l10n_mode'] and changed to tx_eventnews_domain_model_organizer['columns']['starttime']['config']['behaviour']['allowLanguageSynchronization'] = true

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_eventnews_domain_model_organizer['columns']['endtime']['l10n_mode'] and changed to tx_eventnews_domain_model_organizer['columns']['endtime']['config']['behaviour']['allowLanguageSynchronization'] = true

The TCA setting ['ctrl']['requestUpdate'] was removed from table tx_news_domain_model_news. The column field(s) "" and "is_event" were updated and contain option "'onChange' => 'reload'" parallel to 'config' and 'label' section.

The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_news_domain_model_news['columns']['event_end']['config']

The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_eventnews_domain_model_location['columns']['starttime']['config']

The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_eventnews_domain_model_location['columns']['endtime']['config']

The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_eventnews_domain_model_organizer['columns']['starttime']['config']

The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_eventnews_domain_model_organizer['columns']['endtime']['config']

The link wizard has been migrated to a 'renderType' => 'inputLink '. It has been migrated from TCA table "tx_eventnews_domain_model_location['columns']['link']['config']['wizards']['link']" to "tx_eventnews_domain_model_location['columns']['link']['config']['renderType'] = 'inputLink'".

The link wizard has been migrated to a 'renderType' => 'inputLink '. It has been migrated from TCA table "tx_eventnews_domain_model_organizer['columns']['link']['config']['wizards']['link']" to "tx_eventnews_domain_model_organizer['columns']['link']['config']['renderType'] = 'inputLink'".

The config option 'max' has been removed from the TCA for renderType='inputDateTime' in tx_eventnews_domain_model_location['columns']['starttime']['config']['max']

The config option 'max' has been removed from the TCA for renderType='inputDateTime' in tx_eventnews_domain_model_location['columns']['endtime']['config']['max']

The config option 'max' has been removed from the TCA for renderType='inputDateTime' in tx_eventnews_domain_model_organizer['columns']['starttime']['config']['max']

The config option 'max' has been removed from the TCA for renderType='inputDateTime' in tx_eventnews_domain_model_organizer['columns']['endtime']['config']['max']

**Comment by georgringer** [comment]
I improved the TCA a bit. as the mentioned changes are for 8 only and I still support 7x with this release, I can't yet do the changes.
