### ISSUE TITLE
Rename tab "Event details"

### ISSUE THREAD

**Issue by Hawkeye1909** [georgringer/eventnews#134]
Just a minor issue but would you please consider renaming the details tab added by this extension (e.g. to just "Details")? It is odd having it named "Event details" on non-event news... Or is there an easy way to override this?

Greetings!

**Comment by ShortSnow** [comment]
I am confused. If Eventnews is installed. The Bodytext of News is moved to an new tab, called  "Event details".  For using both News and Eventnews it is very confusing to edit the normal News under Event details.

I think there is no need for an extra Tab or it shoul be on News too. 

THX a lot Arne

**Comment by jacobsenj** [comment]
Today I was made aware by a client that this is the case currently:
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/399303/172788849-4b798a34-1b92-47fc-8284-474ee5480816.png">

TYPO3 10 LTS + eventnews 5.0.1

**Comment by baschny** [comment]
Solution from https://github.com/jacobsenj/eventnews/commit/b33569580c0efecac1bf19ebab345743ea19b85f works great, I just created a PR for this - https://github.com/georgringer/eventnews/pull/136
