### ISSUE TITLE
[FEATURE] Recurring events

### ISSUE THREAD

**Issue by BastianBalthasarBux** [georgringer/eventnews#135]
It would be a really great new feature allowing recurring events, like in various calendar applications.
[repeat every day/week/month/year; exception dates]

**Comment by georgringer** [comment]
I won't do that as this really needs lot of time and there are extensions like events2 or calendarize

**Comment by BastianBalthasarBux** [comment]
Okay. Sounds reasonable.
I maybe should have had a look into the closed issues, to see that. ;)
Sorry for wasting your time!

**Comment by georgringer** [comment]
no problem at all ;) closing is faster than building such monster :D
