### ISSUE TITLE
TCA Migrations

### ISSUE THREAD

**Issue by abvdveen** [georgringer/eventnews#140]
Running 'Check TCA Migrations' under 'Upgrade' in typo3 11.5 shows these migrations:

1. The 'tx_eventnews_domain_model_location' TCA configuration 'showRecordFieldList' inside the section 'interface' is not evaluated anymore and should therefore be removed.
2. The 'tx_eventnews_domain_model_organizer' TCA configuration 'showRecordFieldList' inside the section 'interface' is not evaluated anymore and should therefore be removed.
3. The TCA field 'sys_language_uid' of table 'tx_eventnews_domain_model_location' is defined as the 'languageField' and should therefore use the TCA type 'language' instead of TCA type 'select' with 'foreign_table=sys_language' or 'special=languages'.
4. The TCA field 'sys_language_uid' of table 'tx_eventnews_domain_model_organizer' is defined as the 'languageField' and should therefore use the TCA type 'language' instead of TCA type 'select' with 'foreign_table=sys_language' or 'special=languages'.

**Comment by josefglatz** [comment]
@georgringer should I provide the proper patch and respect only typo3 v11? Or is TYPO3 v10 necessary?

**Comment by georgringer** [comment]
I propose adding a custom overrides and change it there for 11, so there is still support for 10
