### ISSUE TITLE
PHP Warning preg_match(): Unknown modifier 'R' in ExtensionManagementUtility.php line 277

### ISSUE THREAD

**Issue by hannesbochmann** [georgringer/eventnews#146]
The changes from #134 introduced a PHP warning "preg_match(): Unknown modifier 'R' in .../typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 277"
This is because the "before:" value in the 4th parameter of the last call to \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToAllTCAtypes() in Configuration/TCA/Overrides/tx_news_domain_model_news.php line 102 is used in a preg_match() call inside a RegEx. Therefore the forward slashes need to be escaped.

I will provide a PR in a moment.

**Comment by liayn** [comment]
https://review.typo3.org/c/Packages/TYPO3.CMS/+/76495

fixed in Core already
