### ISSUE TITLE
Error: Unsupported operand types 

### ISSUE THREAD

**Issue by MarkusBausK** [georgringer/eventnews#15]
Hi,

I updated TYPO3 from 6 to 7.6.18 (everything is fine) an news to the latest version 6.0 (working). After installing eventnews 2.0 I get the following error if I try to open the news-plugin in backend:

```
Unsupported operand types 

Error thrown in file
/html/typo3-pointblog2/typo3conf/ext/eventnews/Classes/Hooks/FlexFormHook.php in line 24.

...
```
If I go back to eventnews 1.2 I can open the plugin without an error.
(Tested with PHP 5.6 and 7.1)

**Comment by georgringer** [comment]
Can you check latest master, I fixed something with latest commit

**Comment by MarkusBausK** [comment]
Seems to work with the latest master. Surprisingly for me because I thought that the master branch is the same as the ter version because of the date... I don't know why I didn't check the latest master to be secure. Maybe you could close this issue.
