### ISSUE TITLE
[BUG] Undefined array key newRecordAsEvent after saving a news

### ISSUE THREAD

**Issue by PKuhlmay** [georgringer/eventnews#154]
Hi after creating a news and hit "save" I get the following error:
<img width="800" alt="Bildschirm­foto 2022-12-02 um 08 45 00" src="https://user-images.githubusercontent.com/107543296/205241869-235666cb-6ea8-4542-9144-dd36d37aa146.png">

I can edit and save an existing news, but not creating a new one.

TYPO3 11.5.19
news 10.0.2
eventnews 5.0.0
PHP 8.1
Composer yes

**Comment by georgringer** [comment]
already solved in 5.0.1, will do a release to ter as well
