### ISSUE TITLE
No events in list view OR event-search not working, depending on version-combination

### ISSUE THREAD

**Issue by mgante** [georgringer/eventnews#16]
Setting up a list view to show up only events results in an empty list, but the backend setting should be correct.

But it brings up the following PHP-Warning:
Core: Error handler (BE): PHP Warning: Declaration of GeorgRinger\Eventnews\Hooks\BackendUtility::updateFlexforms(&$params, &$reference) should be compatible with GeorgRinger\News\Hooks\BackendUtility::updateFlexforms(array &$dataStructure, array $row) in /html/typo3/typo3conf/ext/eventnews/Classes/Hooks/BackendUtility.php line 51

System-Environment:
TYPO3 CMS 7.6.18
PHP Version 7.0.15
news 6.0.0 (also news 5.3.3)
eventnews 1.1.1

-- OTHER SCENARIO --
Setting up a Searchform-Element and a SearchResult-Element from the news-Extension doesn't show any events in the result-list when searching.

A Database-Query-Debug showed, that it searched only for entries with "is_event=0".

Is there any possibility to set up searching also for events or only events?

System-Environment:
TYPO3 CMS 7.6.18
PHP Version 7.0.15
news 6.0.0 (also news 5.3.3)
eventnews 1.2.0

P.S.:
It all works with:
TYPO3 CMS 7.6.11
PHP Version 7.0.9-pl0
news 5.3.3
eventnews 1.1.1

**Comment by mgante** [comment]
I saw your answer on the other open issue and installed the current master from the github-rep.

That seemed to fix the problem. I now have a dropdown for event-restriction in every frontend-plugin of the news-extension.

**Comment by franzkugelmann** [comment]
If you just upgraded to version 2 and now your events are not shown anymore in the frontend list, although you set [no constraint] for the event restriction, and don't want to set a restriction via TS, you can try this:

> plugin.tx_news.settings.overrideFlexformSettingsIfEmpty := removeFromList(eventRestriction)
