### ISSUE TITLE
Compatibility with news v. 11.0.0

### ISSUE THREAD

**Issue by bzgaLindner** [georgringer/eventnews#161]
Due to changes in tx_news (listType to CType etc.), EXT:eventnews does not work with tx_news v 11.0.0 anymore. eventnews 5.0.2 can be installed (non-composer mode), but there is no possibility to select month view.

Would be great if eventnews could be compatible with latest news extension.

Thank you for this awesome extensions!

**Comment by georgringer** [comment]
I plan to make it compatible until end of April. Have you thought about sponsoring the extensions I do?

**Comment by bzgaLindner** [comment]
I'd love to. I use eventnews on a website of a small section of a german union. I will check I they have capacities for sponsoring.

**Comment by kruegerson** [comment]
I just added myself to the list of sponsors - maybe it helps to update eventnews..

**Comment by bzgaLindner** [comment]
> I'd love to. I use eventnews on a website of a small section of a german union. I will check I they have capacities for sponsoring.

Customer agreed to sponsor development.

**Comment by georgringer** [comment]
@bzgaLindner wanna conact me via slack or mail?

**Comment by nabossha** [comment]
would be interested in sponsoring as well for news 11.x and LTS 12 release

**Comment by georgringer** [comment]
you can contact me via email mai @ ringer.it or by slack. however support for v11 and typo3 12 has been done - feel free to test and report success + issues
