### ISSUE TITLE
Unable to extend eventnews Location and Organizer models

### ISSUE THREAD

**Issue by keessonnema** [georgringer/eventnews#168]
My plan was to add new TCA fields to Organizer and Location and use them in the frontend, but after trying and reading through the code we found out that the Classloader in EXT:News is only looking at News and simply ignores eventnews.
https://github.com/georgringer/news/blob/main/Classes/Utility/ClassLoader.php#L132

**What I need**
I want to override the Location and Organizer models with new fields.

**What I got to work**
- I can add custom TCA fields. 
- I can save them in the database
- I can read them in the backend

**What did not work**
- Getting the values of the overridden models in the frontend, they are simply not rendered in {newsItem}, because the classloader cannot find the new fields in EXT:news (I think).

Asked earlier here: https://stackoverflow.com/questions/76313510/how-to-extend-eventnews-location-and-organizer-models-and-render-them-in-the-fr

At this point I'm sure it's just not possible the way I want it to work, but it would be extremely helpful to add custom fields to the Organizer and Location models and group them together with the other fields.

**Comment by birgitberlin** [comment]
Same problem here. 
After upgrading eventnews to v.5.0.2  /TYPO3 v11.x, the added properties in OrganizerModel and LocationModel in my several extensions are ignored in frontend/Fluid. NewsModel works as expected.
How can this be handled now?

Until eventnews v.4.0.0 /TYPO3 v.10.x it works.

**Comment by keessonnema** [comment]
@birgitberlin Georg recommended using the [EXT:extender](https://extensions.typo3.org/extension/extender), although I haven't had it working yet, it seems to be the solution. Georg uses it regularly.

**Comment by birgitberlin** [comment]
Thank you for the hint. It works.

composer require evoweb/extender
```
// ext_localconf.php
$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['my_extension']['extender'][\GeorgRinger\Eventnews\Domain\Model\Location::class]['my_extension'] = \Vendor\MyExtension\Domain\Model\Location::class;
$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['eventnews']['extender'][\GeorgRinger\Eventnews\Domain\Model\Organizer::class]['my_extension'] = \Vendor\MyExtension\Domain\Model\Organizer::class;
```

**Comment by keessonnema** [comment]
@b

**Comment by keessonnema** [comment]
EXT:extender works, but keep in mind that your extension needs a composer.json file with a defined extension_key, otherwise this won't work.
