### ISSUE TITLE
Adding event filter to news list elements

### ISSUE THREAD

**Issue by janslu** [georgringer/eventnews#169]
Is there an easy way to filter out events from news list elements? I want to separate news and events like it was possible in the earlier release but it seems that the news type flex box field is only being added to a month view plugin...

**Comment by georgringer** [comment]
should be fixed with https://github.com/georgringer/eventnews/commit/b2fc94f0457bea11b2886cd1f1a6e2e0f3884cf9

**Comment by janslu** [comment]
Thank you!

**Comment by Hawkeye1909** [comment]
I added these changes and it works as expected. @georgringer Since this is a severe issue with version 6.0.0: when can we expect a new release (or at least tag)?

**Comment by georgringer** [comment]
released now, sry for being late
