### ISSUE TITLE
Static TypoScript should have *.typoscript as file-extension

### ISSUE THREAD

**Issue by julianhofmann** [georgringer/eventnews#181]
Importing TypoScript files with txt-extension does not work anymore in TYPO3 v12.

To avoid trouble with this, the files should be called *.typoscript - or the double-tracked solution: both, txt and typoscript.

**Comment by peterkraume** [comment]
Since the current version of the extension is only available for TYPO3 v11 and v12 it should be sufficent to have only *.typoscript as file extension.
