### ISSUE TITLE
Plugin parameter mount and year dows not work after update from 5.0.0 to 6.0.2

### ISSUE THREAD

**Issue by fischhase** [georgringer/eventnews#196]
Dear Georg,
after upgrading the news and eventnews plugins, the ajax navigation of the calendar dows not work anymore:

`<span onclick="event.stopPropagation();CalendarNav('{f:uri.page(pageUid:currentPageId, additionalParams:{tx_news_pi1:'{overwriteDemand:{month:nextMonthData.month,year:nextMonthData.year}}', type:800})}')" data-url="">></span>
`
the object nextMonthData id correct and the URL seams to be ok: 
`calendar?tx_news_pi1%5BoverwriteDemand%5D%5Bmonth%5D=1&tx_news_pi1%5BoverwriteDemand%5D%5Byear%5D=2025`

But the output is the html of december (today is december). the parameter seam not to be computed.
Would be great if you could have a look.
Thanks und bye
Martin

**Comment by fischhase** [comment]
Achso: TYPO3 11.5.41, PHP 8.3

**Comment by georgringer** [comment]
hey. can you please test latest versions on v12 or v13? or debug the repository calls

**Comment by fischhase** [comment]
Hallo Georg,
good point. I tried in TYPO3 12 and find out, that the next- and previous-link changed fundamentally. I use ajax, so I needed the inline variant of f:uri. 

Old method:
`{f:uri.page(pageUid:currentPageId, additionalParams:{tx_news_pi1:'{overwriteDemand:{month:previousMonthData.month,year:previousMonthData.year}}', type:800})}
`
New method:
`{f:uri.action(controller: 'News', action: 'month', arguments: {overwriteDemand: {month: previousMonthData.month, year: previousMonthData.year}}, pageUid: currentPageId, pageType:800)}`

It happens, because you divided the news and eventnews methods. In the old Version, it was all tx_news. Kept a little time to change the way to generate the correct URL. But maybe it helps someone. 

Thanks for repLy.

**Comment by georgringer** [comment]
thanks for the detailed feedback
