### ISSUE TITLE
Unsupported operand types

### ISSUE THREAD

**Issue by webrealisierung** [georgringer/eventnews#20]
I have the same exception as descriped in this closed issue: https://github.com/georgringer/eventnews/issues/15

I have installed the latest release 2.0.1 of eventnews, I have installed news extension 5.3.3 and Typo3 7.6.16 and php 7.1.6. 

The frontend rendering does work as it should. But when I want to edit the news-template in the backend this exception is thrown:

../typo3conf/ext/eventnews/Classes/Hooks/FlexFormHook.php in line 24.

What is the problem?

**Comment by georgringer** [comment]
fixed in master already
