### ISSUE TITLE
FlexForm not loaded when installed globally

### ISSUE THREAD

**Issue by severinkaderli** [georgringer/eventnews#22]
Hello

I wanted to install this extension globally in typo3/ext and then I saw that the FlexForm wasn't working. After I looked into the I saw that the flexform is hardcoded to load from typo3conf/ in eventnews/Classes/Hooks/FlexFormHook.php

Would it be possible to adjust the path to the one that the extension is installed in?

**Comment by georgringer** [comment]
wanna add a PR? to be honest: the concept of global extensions is dead and you should rethink of using it

**Comment by georgringer** [comment]
closing this. global extension concept is dead
