### ISSUE TITLE
timeRestriction Error on eventnews 2.1.0

### ISSUE THREAD

**Issue by anderlk** [georgringer/eventnews#29]
After update eventnews to Version 2.1.0 with timerestriction setting

`plugin.tx_news.settings.timeRestriction = now`

only articels with endDate set displayed in listView.

**Comment by matt-rein** [comment]
confirm

looks like its broken with PR#21

**Comment by angeloprevitali** [comment]
Can confirm this: If there is NO enddate all the events nothing is displayed anymore since version 2.1.0.

Can you fix this?

Thx & reagrds,
Angelo

**Comment by matt-rein** [comment]
I have changed the following:

eventnews/Classes/Hooks/AbstractDemandedRepository.php

line 104 to 106 with this 3 lines of code

$constraints['timeRestrictionGreater'] = $query->logicalOr(
    $query->greaterThanOrEqual('eventEnd', $timeLimit),
    $query->greaterThanOrEqual('datetime', $timeLimit)

works for me. 
Not sure if this is enough

**Comment by vincentkessels** [comment]
This fix seems to work for me. I think it's best practice to leave the endDate empty for single day events without an end time. Hope to see this in a future release.

Thanks!
