### ISSUE TITLE
Incorrect integer value

### ISSUE THREAD

**Issue by mschmitz89** [georgringer/eventnews#34]
When setting the Event End date to emtpy the following sql error is shown and the changes in this field are discarded.

`2: SQL error: 'Incorrect integer value: '' for column 'event_end' at row 1' (tx_news_domain_model_news:49)`

When translating a news without organizer or location, I get the same error:

`2: SQL error: 'Incorrect integer value: '' for column 'organizer' at row 1' (tx_news_domain_model_news:418)`

When I create a new record in the language I want to translate to and set "Transl.Orig" to the original record in default language, the translation works. But this workaround is not very practicable.

I'm using the TYPO3 8.7.10 and the latest eventnews version 2.1.0

Any help/hints would be greatly appreciated.

**Comment by georgringer** [comment]
Don't use MySQL strict mode or set default value to 0 in tca. Will try to fix it next days

**Comment by mschmitz89** [comment]
Thank you very much for your fast and helpfull reply! :)

I've set 'setDBinit' => 'SET SESSION sql_mode=' but that doesn't have any effect to this.

At TCA/Overrides/tx_news_domain_model_news.php I added 'default' => 0 to event_end, organizer & location. 
For organizer & location this fixed the problem.
For event_end unfortunately not.

**Comment by georgringer** [comment]
for event_end you need to add a new eval as well. see how I fixed it in https://github.com/georgringer/news/commit/15f1126a379c366ef4898eb699c5b9326fff436c#diff-f261e01e8eb94ac44954b21d0e8e975e this is also how it has been changed in the core: https://forge.typo3.org/issues/82756

can you provide a PR for the stuff? that would be great
