### ISSUE TITLE
Date range

### ISSUE THREAD

**Issue by plojewski** [georgringer/eventnews#37]
Hi Georg,
I've got some question. Is it possible to list news which last more than 1 day? For example:

News event is 9.04 but eventEnd is 11.04.

When I click on calendar at 9.04 it display on listing. But when I click 10 or 11.04 news listing is empty.

**Comment by klodeckl** [comment]
+1, same here.

**Comment by georgringer** [comment]
Fixed now, be careful as the template must be changed as well!
