### ISSUE TITLE
Day filter should not be ignored in month view

### ISSUE THREAD

**Issue by klodeckl** [georgringer/eventnews#39]
When a day is selected in month view (in the standard template the arguments for year and month are missing, otherwise it doesn’t work, see my other opened issue) for filtering, the month view should not filter the day because it displays a whole month and a user could think that on the other days there are no events (only in list view the day should be filtered, in month view only month and year).

**Comment by georgringer** [comment]
can you share a link or so, don't really get what you mean

**Comment by klodeckl** [comment]
Here is an example:
https://www.oth-aw.de/informieren-und-entdecken/aktuelles/veranstaltungen/veranstaltungsliste/

When I click on a day on the left calendar view, the other days in the calendar view don’t show an event because it filters that specific day (filtering the day in the list is good, but not in the calendar, user thinks that there is no other event in that month). So the calendar view should not apply the filter for the day.
