### ISSUE TITLE
Duplicate News - SQL Error

### ISSUE THREAD

**Issue by GuillaumeGBzh** [georgringer/eventnews#42]
Hi,

When i duplicate a news record (copy/paste), i get a SQL error ! 

`SQL error: 'Incorrect integer value: '' for column 'organizer' at row 1' (tx_news_domain_model_news:NEW5bab73b822475603994050)`

**Comment by GuillaumeGBzh** [comment]
https://github.com/georgringer/eventnews/commit/9b63694cbdc5978d4f07836b78728f5c80d81305 seems to fix this issue.

Can you release a new version ? 

Thanks.

**Comment by georgringer** [comment]
is planned for next 2 weeks
