### ISSUE TITLE
Filtering does not find a "more day" event

### ISSUE THREAD

**Issue by blueamerican** [georgringer/eventnews#46]
I have an event with start date 15.10. and end date 20.10.

When searching events for 17.10, noting is found.

Is there a way to change this? How?

Example:
http://muster82.md.webseiten.cc/event-news/

If i have an "moredays" event with datetime und eventEnd, e.g.
15. - 18.10. Mitte Oktober Markt,
this is not found in the search Filter if i search for 16.10. - 17.10 

It is only found, if 15.10. is filled in as the startdatum 

How can i resolve this?

**Comment by georgringer** [comment]
Thanks for your report. This is now fixed.
