### ISSUE TITLE
flexform field "eventRestriction" missing

### ISSUE THREAD

**Issue by daniele-c** [georgringer/eventnews#56]
Hi,
since the last update, the flexform field "eventRestriction" is missing in the plugin.
I'm using Typo3 9.5.3.

Thank you for your help!

D.

**Comment by georgringer** [comment]
Did you test master?

**Comment by daniele-c** [comment]
Yes, I'm using the master version. The other tags are not compatible with Typo3 9 yet.

**Comment by georgringer** [comment]
![bildschirmfoto 2019-01-21 um 13 40 59](https://user-images.githubusercontent.com/1905663/51475295-3d206d00-1d82-11e9-8191-8bcc1d9b280b.png)

it is fine for me? don't you see that?

**Comment by daniele-c** [comment]
I'm sorry, it was my mistake. 
I extended the news flexform with a custom field (as described here: https://docs.typo3.org/typo3cms/extensions/news/DeveloperManual/ExtendNews/ExtendFlexforms/Index.html#extend-flexforms-with-custom-fields), but my extension overrides the eventnews flexform. Sorry!!
Thank you for your quick help!
