### ISSUE TITLE
Error in Install-Tool if extension is installed on Analyze Database Structure

### ISSUE THREAD

**Issue by angeloprevitali** [georgringer/eventnews#64]
Hi Georg

if the EXT:eventnews gets installed together with the EXT:news the Analyze Database Structure in the Install Tool cann not be executed due to an Ajax Error. See printscreen.

Furthermore there are a lot of deprecated error messages coming from the EXT:news also.

Composer: No
TYPO3: 9.5.4
EXT:news: 7.0.8
EXT:eventnews: 3.0.0
PHP: 7.1
Linux

Is this error related to the extension OR the the TYPO3 Core?

Thanks for your feedback.

Best regards,
Angelo

![error-eventnews-compare](https://user-images.githubusercontent.com/17588253/53173121-50c02d00-35e7-11e9-863b-45d341f5600f.png)

**Comment by georgringer** [comment]
Hi, this should be solved with current version.
