### ISSUE TITLE
Events on 27.10.2019 will not be shown in calendar view

### ISSUE THREAD

**Issue by owstr** [georgringer/eventnews#65]
27.10.2019 is when daylight saving time will switch. In the list view events on that day are visible, in calendar view not.

PHP 7.2
T3 8.7.24
news 7.0.8
eventnews 3.0.0

Same behavour also on instances with earlier versions of ext.

Best regards,
Oliver

**Comment by georgringer** [comment]
wanna do a PR?

**Comment by owstr** [comment]
Of course i would like to do so. I hadn't the time to read the githubs manual. When i press "new pull request" i leave obviously this fork and go to the cyberhouse pr's. I don't want to do something wrong.

**Comment by owstr** [comment]
Setting [SYS][phpTimeZone] = UTC has solved the problem. Many thanks for the support.
