### ISSUE TITLE
setRespectDay() must be an instance of GeorgRinger\Eventnews\Domain\Model\Dto\void, none returned

### ISSUE THREAD

**Issue by topsnet-holgerd** [georgringer/eventnews#70]
Dear Georg Ringer,
I don't know why but the calendar view is not rendered. I'm getting this error message:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of GeorgRinger\Eventnews\Domain\Model\Dto\Demand::setRespectDay() must be an instance of GeorgRinger\Eventnews\Domain\Model\Dto\void, none returned | TypeError thrown in file /var/www/virtual/dgia.tops.net/htdocs/typo3conf/ext/eventnews/Classes/Domain/Model/Dto/Demand.php in line 165.
Any idea, how this can be make to work?

**Comment by topsnet-holgerd** [comment]
Sorry, forgot the system specifications:
PHP 7.2
T3 8.7.24
news 7.0.8
eventnews 3.0.0

**Comment by georgringer** [comment]
Are you sure it is php 7.2, but yes error is easy to fix

**Comment by topsnet-holgerd** [comment]
Dear Georg,
 
yes, I tried 7.0, 7.1 and at last 7.2, the error did not change regardless of php version.
 
Best wishes,
Holger
 
Von: Georg Ringer <notifications@github.com> 
Gesendet: Montag, 8. April 2019 15:22
An: georgringer/eventnews <eventnews@noreply.github.com>
Cc: topsnet-holgerd <hd@tops.net>; Author <author@noreply.github.com>
Betreff: Re: [georgringer/eventnews] setRespectDay() must be an instance of GeorgRinger\Eventnews\Domain\Model\Dto\void, none returned (#70)
 
Are you sure it is php 7.2, but yes error is easy to fix

**Comment by georgringer** [comment]
Can you check out https://github.com/georgringer/eventnews/commit/589f8a87edd8e3390b83f3f357ed0bfb356a27e4

**Comment by topsnet-holgerd** [comment]
Will do it in the next hours or tomorrow …
 
Von: Georg Ringer <notifications@github.com> 
Gesendet: Montag, 8. April 2019 15:53
An: georgringer/eventnews <eventnews@noreply.github.com>
Cc: topsnet-holgerd <hd@tops.net>; Author <author@noreply.github.com>
Betreff: Re: [georgringer/eventnews] setRespectDay() must be an instance of GeorgRinger\Eventnews\Domain\Model\Dto\void, none returned (#70)
 
Can you check out 589f8a8
